export default {
  MOVIES: "MOVIES",
  CURRENT_PAGE: "CURRENT_PAGE",
  TOGGGLE_LOADER: "TOGGGLE_LOADER",
  REMOVE_MOVIE: "REMOVE_MOVIE",
  SEARCH_TOGGLE: "SEARCH_TOGGLE",
  SHOW_NOTIFY_TOAST: "SHOW_NOTIFY_TOAST",
};